config/routes.rb
Rails.application.routes.draw do
  get 'stores/index'
  get 'book/index/:id' => 'book#index', as: 'book'
  get 'about/index'
  get 'book/lists' => 'startup#index'
  root to: 'startup#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
 end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
	validates :title, :author, :genre_name, presence: true
  	validates :title, uniqueness: true

  	has_many :book_genres
	has_many :genres, through: :book_genres
	has_many :reviews
end

app/models/book_genre.rb
class BookGenre < ApplicationRecord
  belongs_to :book
  belongs_to :genre
end

app/models/genre.rb
class Genre < ApplicationRecord
	validates :title, presence: true
	validates :title, uniqueness: true

	has_many :book_genres
	has_many :books, through: :book_genres
end

app/models/review.rb
class Review < ApplicationRecord
	validates :title, presence: true
	validates :title, uniqueness: true
end

app/models/store.rb
class Store < ApplicationRecord
	validates :name, :address, :latitude, :longitude, presence: true
	validates :latitude, :longitude, numericality: true

	has_many :books
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/book_controller.rb
class BookController < ApplicationController
  def index
  	@book = Book.find(params[:id])
  	book = @book.title
  	@reviews = Review.where(["book_title = '#{book}'"])
  end
end

app/controllers/startup_controller.rb
class StartupController < ApplicationController
  def index
  	@books = Book.where(["title LIKE ?", "%#{params[:search]}%"]).order(:title).page params[:page]
  end
end

app/controllers/stores_controller.rb
class StoresController < ApplicationController
  def index
  	@stores = Store.order(:name)
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_helper.rb
module BookHelper
end

app/helpers/startup_helper.rb
module StartupHelper
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/views/about/index.html.erb
<div class="container mt-5 mb-5 col-md-8 bg-light rounded p-3">
	<h1>Intro Project - Full Stack</h1>
	<p>This is my intro project for full stack web development called iBooks. It is a web app that displays a collection of books and stores.</p>
	<h1>Data Structure</h1>
	<p>- I used Faker to generate all the data I need to my database.</p>
	<p>- Faker::Book - used for Book Table</p>
	<p>- Faker::Book.genre - Used for Genre Table</p>
	<p>- Faker::Address - Used for Store full_address and latitude/longitude</p>
	<p>- Faker::Coffee - Used name for Store name</p>
</div>

app/views/book/index.html.erb
<div class="container mt-5 mb-5 col-md-8 bg-light rounded p-3">
	<div class="row">
		<div class="deal-container col-md-12 col-lg-4 border shadow-sm p-3 bg-light rounded m-0 mt-2 mx-auto">
			<h1><%= @book.title %></h1>
			<small>Created at: <%= @book.created_at %></small>
			<hr>			
			<small>Author: <%= @book.author %></small><br>
			<small>Publisher: <%= @book.publisher %></small><br>
			<small>Genre: <%= @book.genre_name %></small><br>
			<hr>
			<small>Last update: <%= @book.updated_at %></small>
		</div>
	</div>
	<div class="row">	
	<% if @reviews.count > 0 %>
	<div class="deal-container col-md-12 col-lg-4 border shadow-sm p-3 bg-light rounded m-0 mt-2 mx-auto">
	<h1>Reviews</h1>
	<hr>
		<% @reviews.each do |review| %>			
			<h3><%= review.title %></h3>
			<small>Created at: <%= review.created_at %></small>					
			<p><%= review.comment %></p>
			<hr>			
		<% end %>
	</div>	
	<% else %>
		<div class="container col-md-12 col-lg-4 border shadow-sm p-3 bg-light rounded m-0 mt-2 mx-auto">
			<h1>No Reviews Available</h1>
		</div>
	<% end %>
	</div>
</div>
		

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyProject</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
    <%= link_to "iBooks", root_path, :class => "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarColor01">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <%= link_to "Home", book_lists_path, :class => "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Stores Locations", stores_index_path, :class => "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "About", about_index_path, :class => "nav-link" %>
        </li>
      </ul>

      <%= form_tag root_path, :class => "form-inline my-2 my-lg-0", :method => 'get' do %>
        <%= text_field_tag :search, params[:search], :class => "form-control mr-sm-2" %>
        <%= submit_tag "Search", :class => "btn btn-secondary my-2 my-sm-0" %>
      <% end %>

    </div>
  </nav> 

    <%= yield %>
    
  <!-- Footer -->
    <footer>
      <div class="container">
        <div class="row">
          <div class="col-md-4">
            <span class="copyright">Copyright &copy; Intro Project @ Nikko 2018</span>
          </div>
          <div class="col-md-4">
            <ul class="list-inline social-buttons">
              <li class="list-inline-item">
                <a href="#">
                  <i class="fab fa-twitter"></i>
                </a>
              </li>
              <li class="list-inline-item">
                <a href="#">
                  <i class="fab fa-facebook-f"></i>
                </a>
              </li>
              <li class="list-inline-item">
                <a href="#">
                  <i class="fab fa-linkedin-in"></i>
                </a>
              </li>
            </ul>
          </div>
          <div class="col-md-4">
            <ul class="list-inline quicklinks">
              <li class="list-inline-item">
                <a href="#">Privacy Policy</a>
              </li>
              <li class="list-inline-item">
                <a href="#">Terms of Use</a>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>

app/views/startup/index.html.erb
<div class="container col-md-12 col-lg-8">
	<div class="row" >
		<% if @books.count > 0 %>
			<% @books.each do |book| %>
				<div class="container col-md-12 col-lg-4 border shadow-sm p-3 bg-light rounded m-0 mt-2 mx-auto">
					<%= link_to book.title, book_path(book.id), :class => "text-truncate h2" %>
					<hr>
					<small>By: <%= book.author %></small>
				</div>
			<% end %>
		<% else %>
			<div class="container col-md-12 col-lg-4 border shadow-sm p-3 bg-light rounded m-0 mt-2 mx-auto">
				<h1>No Book Available</h1>
			</div>
		<% end %>
	</div>
	<div class="row mt-2 justify-content-center align-items-center">
		<ul class="pagination">
			<%= paginate @books %>	
		</ul>		
	</div>       
</div>

app/views/stores/index.html.erb
<div class="container mt-4 col-sm-12 col-lg-8 bg-light p-4 rounded mb-5">
  <div id="map" class="mt-2" ></div>
</div>


<style>
  /* Set the size of the div element that contains the map */
  #map {
    height: 750px;  /* The height is 750 pixels */
    width: 100%;  /* The width is the width of the web page */
    border-style: solid;
   }
</style>
<script>
  // Initialize and add the map
  function initMap() {    
    // The location based on the address provided
    var option = {
    zoom:18,
    center:({lat: 49.8951, lng: 97.1384})
    }

    infoWindow = new google.maps.InfoWindow;

    // generates google map
    var map = new 
    google.maps.Map(document.getElementById('map'), option);

    current_location();

    <% @stores.each do |store| %>
		addMarker({coords:{ lat: <%= store.latitude %>, 
                    lng: <%= store.longitude %>},
                    content: '<h2><%= store.name %></h2><h3><%= store.address %></h3>'
        });
	<% end %>

    // Handles the current location of the device; if browser is not supported or not allowing location, show errorMessage;
    function current_location() {
      // Locates current location of the device
      if (navigator.geolocation) {
        navigator.geolocation.getCurrentPosition(function(position) {

          var pos = {
            lat: position.coords.latitude,
            lng: position.coords.longitude
          };

          infoWindow.setPosition(pos);
          infoWindow.setContent("<h4>You're here</h4>");
          infoWindow.open(map);
          map.setCenter(pos);

        }, function() {
          handleLocationError(true, infoWindow, map.getCenter());
        });
      } else {
        // Browser doesn't support Geolocation
        handleLocationError(false, infoWindow, map.getCenter());
      }
    }

    // Handles Error messages when the googleMap couldn't locate your current location; browser is does not support geolocation
    function handleLocationError(browserHasGeolocation, infoWindow, pos) {
      infoWindow.setPosition(pos);
      infoWindow.setContent(browserHasGeolocation ?
                            'Error: The Geolocation service failed.' :
                            'Error: Your browser doesn\'t support geolocation.');
      infoWindow.open(map);
    }

    // Add marker function
    function addMarker(props) {
      var marker = new google.maps.Marker({
        position:props.coords,
        map:map
      });

      // checks if there is a content
      if(props.content)
      {
        // creates a new content window for each marker
        var infoWindow = new google.maps.InfoWindow({
          content:props.content
        });

        // add a listener that opens the window when the marker is clicked
        marker.addListener('click', function(){
          infoWindow.open(map, marker);
        });
      }
    }
  }
</script>

<script async defer src="https://maps.googleapis.com/maps/api/js?key=AIzaSyA8etXtYj5InIxhybRUxdmD5LY731EOHUI&callback=initMap">
</script>